language: node_js
node_js:
  - '14'
cache:
  yarn: true
  directories:
    - node_modules
services: # https://docs.travis-ci.com/user/database-setup/
  - mongodb
before_install: cd ./client
install:
  - npm install -g npm@3.10.7 # downgrade to resolve build error
  - npm install
script:
  - cd ../server
  - npm install
  - yarn test
deploy:
  provider: heroku
  api_key:
    secure: "2da7bede-6bf1-42fd-aabc-5a03905fe5d3"
